const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

test('renderer exposes a clear signed-out entry and signed-in finance surfaces', () => {
  const html = fs.readFileSync(path.join(__dirname, '../src/renderer/index.html'), 'utf8');
  assert.match(html, /id="platform-login-modal"/);
  assert.match(html, /id="platform-account"/);
  assert.doesNotMatch(html, /id="account-limit"/);
  assert.match(html, /class="sidebar-footer"[\s\S]*id="platform-account"/);
  assert.match(html, /id="platform-account-menu"/);
  assert.match(html, /id="platform-account-change-password"/);
  assert.match(html, /id="platform-account-logout"/);
  assert.match(html, /id="wallet-view"/);
  assert.match(html, /id="team-view"/);
  assert.match(html, /id="payment-view"/);
  assert.match(html, /data-platform-auth-mode="register"/);
  assert.match(html, /id="platform-login-form"/);
  assert.match(html, /id="platform-register-form"/);
  assert.match(html, /id="platform-reset-form"/);
  assert.match(html, /id="platform-register-request-code"/);
  assert.match(html, /id="platform-reset-request-code"/);
  assert.match(html, /id="platform-wechat-start"/);
  assert.match(html, /id="platform-wechat-frame"/);
  assert.match(html, /id="platform-wechat-refresh"/);
  assert.match(html, /id="platform-wechat-countdown"/);
  assert.match(html, /class="platform-auth-brand"/);
  assert.match(html, /id="platform-login-server-error"/);
  assert.match(html, /id="platform-register-server-error"/);
  assert.match(html, /id="platform-reset-server-error"/);
  assert.match(html, /id="platform-register-form"[\s\S]*?<span>注册<\/span>/);
  assert.match(html, /id="platform-reset-form"[\s\S]*?<span>提交<\/span>/);
  assert.match(html, /platform-field-error/);
  assert.match(html, /class="platform-auth-feedback"/);
  assert.match(html, /platform-auth-illustration\.png/);
  assert.match(html, /本地商家的店铺监控助手/);
  assert.match(html, /更专注，更高效/);
  assert.match(html, /让生意看得更清楚/);
  assert.match(html, /data-password-toggle="platform-login-password"/);
  assert.match(html, /data-password-toggle="platform-register-password"/);
  assert.match(html, /data-password-toggle="platform-reset-password"/);
  assert.match(html, /id="platform-register-password"[^>]*maxlength="20"/);
  assert.match(html, /id="platform-reset-password"[^>]*maxlength="20"/);
  assert.match(html, /assets\/wechat-mark\.svg/);
  assert.doesNotMatch(html, /id="platform-login-close"/);
  assert.doesNotMatch(html, /id="platform-auth-tabs"/);
});
